// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_firewall_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FirewallGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Firewall Group to look up.",
				MarkdownDescription: "The ID of the Firewall Group to look up.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "Timestamp of the last Terraform update of the Firewall Group.",
				MarkdownDescription: "Timestamp of the last Terraform update of the Firewall Group.",
			},
			"members": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The members of the Firewall Group.",
				MarkdownDescription: "The members of the Firewall Group.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Firewall Group.",
				MarkdownDescription: "The name of the Firewall Group.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the Firewall Group is associated with.",
				MarkdownDescription: "The name of the site the Firewall Group is associated with.",
			},
			"site_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the site the Firewall Group is associated with.",
				MarkdownDescription: "The ID of the site the Firewall Group is associated with.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The type of the Firewall Group. Must be one of: `address-group`, `port-group`, or `ipv6-address-group`.",
				MarkdownDescription: "The type of the Firewall Group. Must be one of: `address-group`, `port-group`, or `ipv6-address-group`.",
				Validators: []validator.String{
					stringvalidator.OneOf("address-group", "port-group", "ipv6-address-group"),
				},
			},
		},
	}
}

type FirewallGroupModel struct {
	Id          types.String `tfsdk:"id"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Members     types.List   `tfsdk:"members"`
	Name        types.String `tfsdk:"name"`
	Site        types.String `tfsdk:"site"`
	SiteId      types.String `tfsdk:"site_id"`
	Type        types.String `tfsdk:"type"`
}
