// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_accounts

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AccountsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"accounts": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The ID of the Account.",
							MarkdownDescription: "The ID of the Account.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The name of the Account.",
							MarkdownDescription: "The name of the Account.",
						},
						"network_id": schema.StringAttribute{
							Computed:            true,
							Description:         "ID of the network for the Account.",
							MarkdownDescription: "ID of the network for the Account.",
						},
						"password": schema.StringAttribute{
							Computed:            true,
							Sensitive:           true,
							Description:         "The password of the Account.",
							MarkdownDescription: "The password of the Account.",
						},
						"tunnel_medium_type": schema.Int64Attribute{
							Computed:            true,
							Description:         "See RFC2868 section 3.2. @TODO: better documentation https://help.ui.com/hc/en-us/articles/360015268353-UniFi-USG-UDM-Configuring-RADIUS-Server#6",
							MarkdownDescription: "See RFC2868 section 3.2. @TODO: better documentation https://help.ui.com/hc/en-us/articles/360015268353-UniFi-USG-UDM-Configuring-RADIUS-Server#6",
						},
						"tunnel_type": schema.Int64Attribute{
							Computed:            true,
							Description:         "See RFC2868 section 3.1. @TODO: better documentation https://help.ui.com/hc/en-us/articles/360015268353-UniFi-USG-UDM-Configuring-RADIUS-Server#6",
							MarkdownDescription: "See RFC2868 section 3.1. @TODO: better documentation https://help.ui.com/hc/en-us/articles/360015268353-UniFi-USG-UDM-Configuring-RADIUS-Server#6",
						},
					},
					CustomType: AccountsType{
						ObjectType: types.ObjectType{
							AttrTypes: AccountsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "The list of Accounts associated with the site.",
				MarkdownDescription: "The list of Accounts associated with the site.",
			},
			"site": schema.StringAttribute{
				Optional:            true,
				Description:         "The name of the site the Accounts are associated with.",
				MarkdownDescription: "The name of the site the Accounts are associated with.",
			},
		},
	}
}

type AccountsModel struct {
	Accounts types.List   `tfsdk:"accounts"`
	Site     types.String `tfsdk:"site"`
}

var _ basetypes.ObjectTypable = AccountsType{}

type AccountsType struct {
	basetypes.ObjectType
}

func (t AccountsType) Equal(o attr.Type) bool {
	other, ok := o.(AccountsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccountsType) String() string {
	return "AccountsType"
}

func (t AccountsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return nil, diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return nil, diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	tunnelMediumTypeAttribute, ok := attributes["tunnel_medium_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_medium_type is missing from object`)

		return nil, diags
	}

	tunnelMediumTypeVal, ok := tunnelMediumTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_medium_type expected to be basetypes.Int64Value, was: %T`, tunnelMediumTypeAttribute))
	}

	tunnelTypeAttribute, ok := attributes["tunnel_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_type is missing from object`)

		return nil, diags
	}

	tunnelTypeVal, ok := tunnelTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_type expected to be basetypes.Int64Value, was: %T`, tunnelTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccountsValue{
		Id:               idVal,
		Name:             nameVal,
		NetworkId:        networkIdVal,
		Password:         passwordVal,
		TunnelMediumType: tunnelMediumTypeVal,
		TunnelType:       tunnelTypeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewAccountsValueNull() AccountsValue {
	return AccountsValue{
		state: attr.ValueStateNull,
	}
}

func NewAccountsValueUnknown() AccountsValue {
	return AccountsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccountsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccountsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccountsValue Attribute Value",
				"While creating a AccountsValue value, a missing attribute value was detected. "+
					"A AccountsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccountsValue Attribute Type",
				"While creating a AccountsValue value, an invalid attribute value was detected. "+
					"A AccountsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccountsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccountsValue Attribute Value",
				"While creating a AccountsValue value, an extra attribute value was detected. "+
					"A AccountsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccountsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccountsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	passwordAttribute, ok := attributes["password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	passwordVal, ok := passwordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password expected to be basetypes.StringValue, was: %T`, passwordAttribute))
	}

	tunnelMediumTypeAttribute, ok := attributes["tunnel_medium_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_medium_type is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	tunnelMediumTypeVal, ok := tunnelMediumTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_medium_type expected to be basetypes.Int64Value, was: %T`, tunnelMediumTypeAttribute))
	}

	tunnelTypeAttribute, ok := attributes["tunnel_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tunnel_type is missing from object`)

		return NewAccountsValueUnknown(), diags
	}

	tunnelTypeVal, ok := tunnelTypeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tunnel_type expected to be basetypes.Int64Value, was: %T`, tunnelTypeAttribute))
	}

	if diags.HasError() {
		return NewAccountsValueUnknown(), diags
	}

	return AccountsValue{
		Id:               idVal,
		Name:             nameVal,
		NetworkId:        networkIdVal,
		Password:         passwordVal,
		TunnelMediumType: tunnelMediumTypeVal,
		TunnelType:       tunnelTypeVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewAccountsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccountsValue {
	object, diags := NewAccountsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccountsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccountsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccountsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccountsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccountsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccountsValueMust(AccountsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccountsType) ValueType(ctx context.Context) attr.Value {
	return AccountsValue{}
}

var _ basetypes.ObjectValuable = AccountsValue{}

type AccountsValue struct {
	Id               basetypes.StringValue `tfsdk:"id"`
	Name             basetypes.StringValue `tfsdk:"name"`
	NetworkId        basetypes.StringValue `tfsdk:"network_id"`
	Password         basetypes.StringValue `tfsdk:"password"`
	TunnelMediumType basetypes.Int64Value  `tfsdk:"tunnel_medium_type"`
	TunnelType       basetypes.Int64Value  `tfsdk:"tunnel_type"`
	state            attr.ValueState
}

func (v AccountsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["network_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tunnel_medium_type"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["tunnel_type"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.NetworkId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_id"] = val

		val, err = v.Password.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password"] = val

		val, err = v.TunnelMediumType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tunnel_medium_type"] = val

		val, err = v.TunnelType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tunnel_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccountsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccountsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccountsValue) String() string {
	return "AccountsValue"
}

func (v AccountsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":                 basetypes.StringType{},
		"name":               basetypes.StringType{},
		"network_id":         basetypes.StringType{},
		"password":           basetypes.StringType{},
		"tunnel_medium_type": basetypes.Int64Type{},
		"tunnel_type":        basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":                 v.Id,
			"name":               v.Name,
			"network_id":         v.NetworkId,
			"password":           v.Password,
			"tunnel_medium_type": v.TunnelMediumType,
			"tunnel_type":        v.TunnelType,
		})

	return objVal, diags
}

func (v AccountsValue) Equal(o attr.Value) bool {
	other, ok := o.(AccountsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.NetworkId.Equal(other.NetworkId) {
		return false
	}

	if !v.Password.Equal(other.Password) {
		return false
	}

	if !v.TunnelMediumType.Equal(other.TunnelMediumType) {
		return false
	}

	if !v.TunnelType.Equal(other.TunnelType) {
		return false
	}

	return true
}

func (v AccountsValue) Type(ctx context.Context) attr.Type {
	return AccountsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccountsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":                 basetypes.StringType{},
		"name":               basetypes.StringType{},
		"network_id":         basetypes.StringType{},
		"password":           basetypes.StringType{},
		"tunnel_medium_type": basetypes.Int64Type{},
		"tunnel_type":        basetypes.Int64Type{},
	}
}
