// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_setting_usg

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SettingUsgResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"dhcp_relay_servers": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The DHCP relay servers.",
				MarkdownDescription: "The DHCP relay servers.",
				Validators: []validator.List{
					listvalidator.SizeAtMost(5),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Setting USG.",
				MarkdownDescription: "The ID of the Setting USG.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "Timestamp of the last Terraform update of the Setting USG.",
				MarkdownDescription: "Timestamp of the last Terraform update of the Setting USG.",
			},
			"multicast_dns_enabled": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether multicast DNS is enabled.",
				MarkdownDescription: "Whether multicast DNS is enabled.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the Setting USG is associated with.",
				MarkdownDescription: "The name of the site the Setting USG is associated with.",
			},
			"site_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the site the Setting USG is associated with.",
				MarkdownDescription: "The id of the site the Setting USG is associated with.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

type SettingUsgModel struct {
	DhcpRelayServers    types.List   `tfsdk:"dhcp_relay_servers"`
	Id                  types.String `tfsdk:"id"`
	LastUpdated         types.String `tfsdk:"last_updated"`
	MulticastDnsEnabled types.Bool   `tfsdk:"multicast_dns_enabled"`
	Site                types.String `tfsdk:"site"`
	SiteId              types.String `tfsdk:"site_id"`
}
