// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_radius_profile

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func RadiusProfileDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of this RADIUS Profile.",
				MarkdownDescription: "The ID of this RADIUS Profile.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of this RADIUS Profile.",
				MarkdownDescription: "The name of this RADIUS Profile.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the RADIUS Profile is associated with.",
				MarkdownDescription: "The name of the site the RADIUS Profile is associated with.",
			},
		},
	}
}

type RadiusProfileModel struct {
	Id   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
	Site types.String `tfsdk:"site"`
}
