// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_site

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SiteDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the Site.",
				MarkdownDescription: "The description of the Site.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Site to look up.",
				MarkdownDescription: "The ID of the Site to look up.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the Site.",
				MarkdownDescription: "The name of the Site.",
			},
		},
	}
}

type SiteModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
}
