// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_static_route

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func StaticRouteDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"distance": schema.Int64Attribute{
				Computed:            true,
				Description:         "The distance of the Static Route.",
				MarkdownDescription: "The distance of the Static Route.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Static Route to look up.",
				MarkdownDescription: "The ID of the Static Route to look up.",
			},
			"interface": schema.StringAttribute{
				Computed:            true,
				Description:         "The interface of the Static Route (only valid for `interface-route` type). This can be `WAN1`, `WAN2`, or a network ID.",
				MarkdownDescription: "The interface of the Static Route (only valid for `interface-route` type). This can be `WAN1`, `WAN2`, or a network ID.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the Static Route.",
				MarkdownDescription: "The name of the Static Route.",
			},
			"network": schema.StringAttribute{
				Computed:            true,
				Description:         "The network subnet address.",
				MarkdownDescription: "The network subnet address.",
			},
			"next_hop": schema.StringAttribute{
				Computed:            true,
				Description:         "The next hop of the Static Route (only valid for `nexthop-route` type).",
				MarkdownDescription: "The next hop of the Static Route (only valid for `nexthop-route` type).",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the Static Rotue is associated with.",
				MarkdownDescription: "The name of the site the Static Rotue is associated with.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "The type of Static Route. Can be `interface-route`, `nexthop-route`, or `blackhole`.",
				MarkdownDescription: "The type of Static Route. Can be `interface-route`, `nexthop-route`, or `blackhole`.",
			},
		},
	}
}

type StaticRouteModel struct {
	Distance  types.Int64  `tfsdk:"distance"`
	Id        types.String `tfsdk:"id"`
	Interface types.String `tfsdk:"interface"`
	Name      types.String `tfsdk:"name"`
	Network   types.String `tfsdk:"network"`
	NextHop   types.String `tfsdk:"next_hop"`
	Site      types.String `tfsdk:"site"`
	Type      types.String `tfsdk:"type"`
}
