// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_radius_profile

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RadiusProfileResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of this RADIUS Profile.",
				MarkdownDescription: "The ID of this RADIUS Profile.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "Timestamp of the last Terraform update of the RADIUS Profile.",
				MarkdownDescription: "Timestamp of the last Terraform update of the RADIUS Profile.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of this RADIUS Profile.",
				MarkdownDescription: "The name of this RADIUS Profile.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the RADIUS Profile is associated with.",
				MarkdownDescription: "The name of the site the RADIUS Profile is associated with.",
			},
			"site_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the site the RADIUS Profile is associated with.",
				MarkdownDescription: "The id of the site the RADIUS Profile is associated with.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

type RadiusProfileModel struct {
	Id          types.String `tfsdk:"id"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Name        types.String `tfsdk:"name"`
	Site        types.String `tfsdk:"site"`
	SiteId      types.String `tfsdk:"site_id"`
}
