// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the User Group to look up.",
				MarkdownDescription: "The ID of the User Group to look up.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of this User Group.",
				MarkdownDescription: "The name of this User Group.",
			},
			"qos_rate_max_down": schema.Int64Attribute{
				Computed:            true,
				Description:         "QOS max download rate for the User Group.",
				MarkdownDescription: "QOS max download rate for the User Group.",
			},
			"qos_rate_max_up": schema.Int64Attribute{
				Computed:            true,
				Description:         "QOS max upload rate for the User Group.",
				MarkdownDescription: "QOS max upload rate for the User Group.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the User Group is associated with.",
				MarkdownDescription: "The name of the site the User Group is associated with.",
			},
		},
	}
}

type UserGroupModel struct {
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	QosRateMaxDown types.Int64  `tfsdk:"qos_rate_max_down"`
	QosRateMaxUp   types.Int64  `tfsdk:"qos_rate_max_up"`
	Site           types.String `tfsdk:"site"`
}
