// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_unifi

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func UnifiProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_insecure": schema.BoolAttribute{
				Optional:            true,
				Description:         "Allow insecure connections to the Unifi Controller by not checking for things like self signed certificates. Don't use in Production.",
				MarkdownDescription: "Allow insecure connections to the Unifi Controller by not checking for things like self signed certificates. Don't use in Production.",
			},
			"api_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The API Key to use to connect to the Unifi Controller.",
				MarkdownDescription: "The API Key to use to connect to the Unifi Controller.",
			},
			"host": schema.StringAttribute{
				Required:            true,
				Description:         "The host address of the Unifi Controller.",
				MarkdownDescription: "The host address of the Unifi Controller.",
			},
		},
	}
}

type UnifiModel struct {
	AllowInsecure types.Bool   `tfsdk:"allow_insecure"`
	ApiKey        types.String `tfsdk:"api_key"`
	Host          types.String `tfsdk:"host"`
}
