// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_setting_usg

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SettingUsgDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"dhcp_relay_servers": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The DHCP relay servers.",
				MarkdownDescription: "The DHCP relay servers.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The ID of the Setting USG.",
				MarkdownDescription: "The ID of the Setting USG.",
			},
			"multicast_dns_enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether multicast DNS is enabled.",
				MarkdownDescription: "Whether multicast DNS is enabled.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the Setting USG is associated with.",
				MarkdownDescription: "The name of the site the Setting USG is associated with.",
			},
			"site_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the site the Setting USG is associated with.",
				MarkdownDescription: "The id of the site the Setting USG is associated with.",
			},
		},
	}
}

type SettingUsgModel struct {
	DhcpRelayServers    types.List   `tfsdk:"dhcp_relay_servers"`
	Id                  types.String `tfsdk:"id"`
	MulticastDnsEnabled types.Bool   `tfsdk:"multicast_dns_enabled"`
	Site                types.String `tfsdk:"site"`
	SiteId              types.String `tfsdk:"site_id"`
}
