// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ap_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ApGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"device_macs": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The MAC addresses of the APs associated with this AP Group.",
				MarkdownDescription: "The MAC addresses of the APs associated with this AP Group.",
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The ID of the AP Group to look up.",
				MarkdownDescription: "The ID of the AP Group to look up.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of this AP Group.",
				MarkdownDescription: "The name of this AP Group.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the AP Group is associated with.",
				MarkdownDescription: "The name of the site the AP Group is associated with.",
			},
		},
	}
}

type ApGroupModel struct {
	DeviceMacs types.List   `tfsdk:"device_macs"`
	Id         types.String `tfsdk:"id"`
	Name       types.String `tfsdk:"name"`
	Site       types.String `tfsdk:"site"`
}
