// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_firewall_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func FirewallGroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the Firewall Group to look up.",
				MarkdownDescription: "The ID of the Firewall Group to look up.",
			},
			"members": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The members of the Firewall Group.",
				MarkdownDescription: "The members of the Firewall Group.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the Firewall Group.",
				MarkdownDescription: "The name of the Firewall Group.",
			},
			"site": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the site the Firewall Group is associated with.",
				MarkdownDescription: "The name of the site the Firewall Group is associated with.",
			},
			"site_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the site the Firewall Group is associated with.",
				MarkdownDescription: "The name of the site the Firewall Group is associated with.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "The type of the Firewall Group. Must be one of: `address-group`, `port-group`, or `ipv6-address-group`.",
				MarkdownDescription: "The type of the Firewall Group. Must be one of: `address-group`, `port-group`, or `ipv6-address-group`.",
			},
		},
	}
}

type FirewallGroupModel struct {
	Id      types.String `tfsdk:"id"`
	Members types.List   `tfsdk:"members"`
	Name    types.String `tfsdk:"name"`
	Site    types.String `tfsdk:"site"`
	SiteId  types.String `tfsdk:"site_id"`
	Type    types.String `tfsdk:"type"`
}
